version: '3.8'

services:
  starch-mine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starch-mine
    restart: unless-stopped
    volumes:
      - ./miner.conf:/starch-mine/miner.conf
